general: use Exception.add_note instead of hacky my.core.error.echain
before it was dumping a sequence of somewhat confusing exception messages, now it's printing something like this

```
[ERROR   2025-02-04 21:53:13,891 my.instagram.android run.py:9   ] ('<message_id>', "xma_link isn't handled yet")
Traceback (most recent call last):
  File "src/my/instagram/android.py", line 169, in _process_db
    m = _parse_message(j)
        ^^^^^^^^^^^^^^^^^
  File "/code/hpi/src/my/instagram/android.py", line 120, in _parse_message
    raise MessageError(id, f"{t} isn't handled yet")
my.instagram.android.MessageError: ('2932982394892980393664', "xma_link isn't handled yet")
^ while parsing {'status': 'UPLOADED', 'item_type': 'xma_link',...
^ while processing /path/to/db/direct.db
```

for python < 3.11, a backport is used

For more info, see:
- https://peps.python.org/pep-0678
- https://docs.python.org/3/tutorial/errors.html#tut-exception-notes